apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-prom
  labels:
    app: mc-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-prom
  template:
    metadata:
      labels:
        app: mc-prom
    spec:
      containers:
      - name: mc-prom
        image: julienstroheker/mc-prom
        imagePullPolicy: Always
        env:
        - name: MC_SERVER
          value: "openhack-challeng2-svc"
        - name: MC_PASSWORD
          value: "cheesesteakjimmys"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mc-prom-svc
spec:
  ports:
  - port: 8000
  selector:
    app: mc-prom